# Generated by Django 2.2.4 on 2023-03-29 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('신생아작명', '신생아작명'), ('개명', '개명'), ('사주상담', '사주상담'), ('궁합', '궁합'), ('택일', '택일')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parents_name', models.CharField(blank=True, max_length=25)),
                ('first_name_ch', models.CharField(blank=True, max_length=25)),
                ('fav_name', models.CharField(blank=True, max_length=100)),
                ('avoid_name', models.CharField(blank=True, max_length=100)),
                ('adress', models.CharField(blank=True, max_length=100)),
                ('phonnumber', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('gen', models.CharField(max_length=1)),
                ('sl', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('time', models.CharField(choices=[('子시 23:30~01:30', '子시 23:30~01:30'), ('丑시 01:30~03:30', '丑시 01:30~03:30'), ('寅시 03:30~05:30', '寅시 03:30~05:30'), ('卯시 05:30~07:30', '卯시 05:30~07:30'), ('辰시 07:30~09:30', '辰시 07:30~09:30'), ('巳시 09:30~11:30', '巳시 09:30~11:30'), ('午시 11:30~13:30', '午시 11:30~13:30'), ('未시 13:30~15:30', '未시 13:30~15:30'), ('申시 15:30~17:30', '申시 15:30~17:30'), ('酉시 17:30~19:30', '酉시 17:30~19:30'), ('戌시 19:30~21:30', '戌시 19:30~21:30'), ('亥시 21:30~23:30', '亥시 21:30~23:30')], max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='base.Submit')),
            ],
        ),
    ]
