# Generated by Django 3.2.18 on 2023-04-16 08:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phonnumber', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('신생아작명', '신생아작명'), ('개명', '개명'), ('사주상담', '사주상담'), ('궁합', '궁합'), ('택일', '택일')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parents_name', models.CharField(blank=True, max_length=25)),
                ('first_name_ch', models.CharField(blank=True, max_length=25)),
                ('fav_name', models.CharField(blank=True, max_length=100)),
                ('avoid_name', models.CharField(blank=True, max_length=100)),
                ('adress', models.CharField(blank=True, max_length=100)),
                ('phonnumber', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('gen', models.CharField(max_length=1)),
                ('sl', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('time', models.CharField(choices=[('子시 23:31~01:30', '子시 23:31~01:30'), ('丑시 01:31~03:30', '丑시 01:31~03:30'), ('寅시 03:31~05:30', '寅시 03:31~05:30'), ('卯시 05:31~07:30', '卯시 05:31~07:30'), ('辰시 07:31~09:30', '辰시 07:31~09:30'), ('巳시 09:31~11:30', '巳시 09:31~11:30'), ('午시 11:31~13:30', '午시 11:31~13:30'), ('未시 13:31~15:30', '未시 13:31~15:30'), ('申시 15:31~17:30', '申시 15:31~17:30'), ('酉시 17:31~19:30', '酉시 17:31~19:30'), ('戌시 19:31~21:30', '戌시 19:31~21:30'), ('亥시 21:31~23:30', '亥시 21:31~23:30')], max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='base.submit')),
            ],
        ),
    ]
