# Generated by Django 3.2.18 on 2023-04-07 10:15

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230329_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.CharField(choices=[('子시 23:31~01:30', '子시 23:31~01:30'), ('丑시 01:31~03:30', '丑시 01:31~03:30'), ('寅시 03:31~05:30', '寅시 03:31~05:30'), ('卯시 05:31~07:30', '卯시 05:31~07:30'), ('辰시 07:31~09:30', '辰시 07:31~09:30'), ('巳시 09:31~11:30', '巳시 09:31~11:30'), ('午시 11:31~13:30', '午시 11:31~13:30'), ('未시 13:31~15:30', '未시 13:31~15:30'), ('申시 15:31~17:30', '申시 15:31~17:30'), ('酉시 17:31~19:30', '酉시 17:31~19:30'), ('戌시 19:31~21:30', '戌시 19:31~21:30'), ('亥시 21:31~23:30', '亥시 21:31~23:30')], max_length=25),
        ),
        migrations.AlterField(
            model_name='submit',
            name='phonnumber',
            field=models.CharField(max_length=20, validators=[base.validators.only_num]),
        ),
    ]
