# Generated by Django 3.2.18 on 2023-04-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230407_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='phonnumber',
            field=models.CharField(max_length=20),
        ),
    ]
