# Generated by Django 3.2.18 on 2023-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_submit_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='process',
            field=models.CharField(choices=[('입금대기', '입금대기'), ('진행중', '진행중'), ('완료', '완료')], max_length=20, null=True),
        ),
    ]
