# Generated by Django 3.2.18 on 2023-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_phonnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='visit',
            field=models.CharField(choices=[('방문상담', '방문상담'), ('전화상담', '전화상담')], max_length=20, null=True),
        ),
    ]
