# Generated by Django 3.2.18 on 2023-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_submit_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='wantdate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
