# Generated by Django 3.2.18 on 2023-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseryuk', '0008_alter_manseryuk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manseryuk',
            name='yd',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
