# Generated by Django 3.2.18 on 2023-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseryuk', '0010_auto_20230425_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manseryuk',
            name='day',
            field=models.IntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='manseryuk',
            name='month',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='manseryuk',
            name='yd',
            field=models.CharField(choices=[('평달', '평달'), ('윤달', '윤달')], default='평달', max_length=10, null=True),
        ),
    ]
