# Generated by Django 3.2.18 on 2024-03-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseryuk', '0012_auto_20240115_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manseryuk',
            name='day',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='manseryuk',
            name='month',
            field=models.IntegerField(default=3),
        ),
    ]
